---
title: "#TidyTuesday Tour de France"
output: 
  html_document: 
    keep_md: yes
---

```{r cache=TRUE, message=FALSE, warning=FALSE}
# Get the Data

tdf_winners <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_winners.csv')

# libraries
library(tidyverse)
library(lubridate)
library(ggplot2)
```

```{r cache=TRUE}
# clean data
tdf_winners$start_date <- ymd(tdf_winners$start_date)
tdf_winners$born <- ymd(tdf_winners$born)
tdf_winners$died <- ymd(tdf_winners$died)
```


```{r}
tdf_winners %>%
  ggplot(aes(start_date,distance))+
  geom_line()
```

```{r}
tdf_winners %>%
  mutate(avg_speed = distance/time_overall) %>%
  ggplot(aes(start_date,avg_speed))+
  geom_line()
```

```{r}
tdf_winners %>%
  mutate(avg_speed = distance/time_overall) %>%
  ggplot(aes(start_date,avg_speed))+
  geom_smooth()+
  geom_point()+
  geom_line()
```
```{r}
tdf_winners %>%
  mutate(avg_speed = distance/time_overall) %>%
  mutate(decade_start=year(start_date) - year(start_date)%%10) %>%
  ggplot(aes(decade_start,avg_speed,group=decade_start))+
  geom_boxplot()
```