---
title: "squirrel_census"
author: "joedinoto"
date: "10/28/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE,message=FALSE}
library(tidyverse)
library(lubridate)
```


```{r warning=FALSE, message=FALSE}
nyc_squirrels <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-29/nyc_squirrels.csv")
```

```{r}
# clean data
nyc_squirrels$date <- mdy(nyc_squirrels$date)
```


```{r}
# How many unique squirrels are there in central park?
# 3,018
# There are 5 dulplicate squirrels!
nyc_squirrels %>%
  count(unique_squirrel_id, sort=TRUE)
```

```{r}
# Where are the squirrels located?
nyc_squirrels %>%
  select(lat,long)%>%
  summary()
```
```{r}
# Density of squirrels?
nyc_squirrels %>%
  ggplot(aes(long,lat))+
  geom_bin2d()
```


```{r}
# What are the most common kinds of squirrel?
# And when do they come out to play?
nyc_squirrels %>%
  filter(!is.na(primary_fur_color)) %>%
  filter(!is.na(shift)) %>%
  filter(!is.na(age))%>%
  filter(age != "?")%>%
  ggplot(aes(primary_fur_color)) +
  facet_grid(shift ~ age)+
  geom_bar(aes(fill=primary_fur_color)) +
  theme(legend.position = "none")
```

```{r}
# Where are the juvenile vs. adult squirrels in the AM & PM hours?
# what is their primary_fur_color?
nyc_squirrels %>%
  filter(!is.na(primary_fur_color)) %>%
  filter(!is.na(shift)) %>%
  filter(!is.na(age))%>%
  filter(age != "?")%>%
  ggplot(aes(long, lat)) +
  geom_point(aes(color=primary_fur_color),alpha=0.5) +
  coord_equal() +
  facet_grid(shift ~ age)+
  labs(title="one dot equals one squirrel", 
       subtitle = "Central Park, USA")+
  theme(legend.position = "top")
```
```{r}
# primary_fur_color and age by AM or PM
nyc_squirrels %>%
  filter(!is.na(primary_fur_color)) %>%
  filter(!is.na(shift)) %>%
  filter(!is.na(age))%>%
  filter(age != "?")%>%
  ggplot(aes(long, lat)) +
  geom_point(aes(color=shift),alpha=0.5,size=0.1) +
  coord_equal() +
  facet_grid(age ~ primary_fur_color)+
  labs(title="one dot equals one squirrel", 
       subtitle = "Central Park, USA")
```

