---
title: "week-7"
author: "Maxwel Coura Oliveira"
date: "2/13/2021"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE)
```

```{r packages}
library(tidyverse)
library(ggthemes)
library(ggtext)
library(gganimate)
```

```{r import-data}
tuesdata <- tidytuesdayR::tt_load('2021-02-09')
#tuesdata <- tidytuesdayR::tt_load(2021, week = 7)
```


```{r load-data}
retirement <- tuesdata$retirement
```


```{r figure}
retirement %>% 
  ggplot(aes(x = year, y = retirement, group = race, color = race)) +
  geom_label(aes(label = race), show.legend = FALSE) +
  geom_line(aes(color = race), show.legend = FALSE) + 
  scale_y_continuous(n.breaks = 10, 
                     labels = scales::dollar_format(prefix = "$")) +
  scale_x_continuous(limits = c(1989, 2016), n.breaks = 10,
                     labels = scales::label_number(accuracy = 1, 
                                                   big.mark = "")) +
  labs(y = "",
       x = "",
       title = "Retirement savings in the <b style='color:red;'>United States of America</b>",
       subtitle = "The inequality among races has dramatically increased in 25 years",
       caption = "Visualization: @maxwelco | Source: Urban Institute") +
  scale_color_brewer(palette = "Set1")  +
  transition_reveal(along = year) 
```
