---
title: "wealth inequality"
author: "Joe DiNoto"
date: "2/12/2021"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE,error=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(dplyr)
```

```{r message=FALSE, warning=FALSE,error=FALSE}
tuesdata <- tidytuesdayR::tt_load(2021, week = 7)
```


## Percent of student debt over time

```{r}
student_debt<- tuesdata$student_debt

student_debt %>% 
  ggplot(aes(year,loan_debt_pct, fill=race)) + 
  geom_col(position = "dodge")
```
## Income distrubition over time

```{r}
income_time <- tuesdata$income_time

income_time %>%
  ggplot(aes(year, income_family, color=percentile))+
  geom_line(size=3)+
  labs(title="family income over time by income percentile",
       x="",
       y="")+
  scale_y_continuous(labels=scales::dollar_format())
```

# By what percentage did the income change from its initial value over time?
```{r}
# setting initial incomes
initial_10 <- income_time$income_family[1]
initial_50 <- income_time$income_family[2]
initial_90 <- income_time$income_family[3]

income_time %>%
  pivot_wider(names_from = c(percentile), values_from = income_family) %>%
  mutate(pct_10th = `10th`/initial_10) %>%
  mutate(pct_50th = `50th`/initial_50) %>%
  mutate(pct_90th = `90th`/initial_90) %>%
  select(year,pct_10th:pct_90th) %>%
  pivot_longer(pct_10th:pct_90th,names_to = "percentile", values_to="pct_change_from_1963") %>%
  ggplot(aes(year,pct_change_from_1963,color=percentile))+
  geom_line(size=2)+
  labs(title="percent of family income change relative to 1963",
       x="year",
       y="percent growth")

```

```{r}
income_limits <- tuesdata$income_limits
```

```{r}
income_limits %>%
  filter(dollar_type=="2019 Dollars") %>%
  #filter(income_quintile==c("Top 5%","Lowest"))%>%
  #filter(race== c("Asian Alone","White Alone","Black Alone"))%>%
  ggplot(aes(year,income_dollars,color=race)) +
  geom_line()+
  facet_wrap(.~income_quintile)+
  scale_y_continuous(labels=scales::dollar_format()) +
  scale_color_brewer(palette="Set2")
```
```{r}
income_limits %>%
  filter(dollar_type=="2019 Dollars") %>%
  filter(race != "All Races") %>%
  filter(year>=2000)%>%
  ggplot(aes(year,income_dollars,color=income_quintile)) +
  geom_line()+
  facet_wrap(.~race)+
  scale_y_continuous(labels=scales::dollar_format()) +
  scale_color_brewer(palette="Set2")
```
